# Generated by Django 3.0.3 on 2020-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrmCustGblMst',
            fields=[
                ('cust_id', models.AutoField(db_column='CUST_ID', primary_key=True, serialize=False)),
                ('cust_legal_name', models.CharField(db_column='CUST_LEGAL_NAME', max_length=100)),
                ('deploy_type_mst_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='END_DATE', null=True)),
                ('is_active', models.CharField(blank=True, db_column='IS_ACTIVE', max_length=2, null=True)),
                ('prim_contact', models.CharField(blank=True, db_column='PRIM_CONTACT', max_length=100, null=True)),
                ('country',models.CharField(db_column = 'COUNTRY',max_length  =100)),
                ('revenue_range', models.CharField(blank=True, db_column='REVENUE_RANGE', max_length=100, null=True)),
                ('num_employees', models.CharField(blank=True, db_column='NUM_EMPLOYEES', max_length=100, null=True)),
                ('crd_date', models.DateTimeField(blank=True, db_column='CRD_DATE', null=True)),
                ('upd_date', models.DateTimeField()),
                ('upd_usr_id', models.IntegerField(blank=True, db_column='UPD_USR_ID', null=True)),
            ],
            options={
                'db_table': 'irm_cust_gbl_mst',
                'managed': False,
            },
        ),
    ]
