# Generated by Django 3.0.3 on 2020-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrmCustModuleLicenseDtl',
            fields=[
                ('row_id', models.AutoField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('crd_date', models.DateTimeField(blank=True, db_column='CRD_DATE', null=True)),
                ('upd_date', models.DateTimeField()),
                ('crd_usr_id', models.IntegerField(blank=True, db_column='CRD_USR_ID', null=True)),
                ('upd_usr_id', models.IntegerField(blank=True, db_column='UPD_USR_ID', null=True)),
            ],
            options={
                'db_table': 'irm_cust_module_license_dtl',
                'managed': False,
            },
        ),
    ]
