# Generated by Django 3.0.3 on 2020-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrmJobMaster',
            fields=[
                ('irm_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('irm_job_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('irm_cust_id', models.IntegerField(blank=True, null=True)),
                ('irm_run_date', models.DateTimeField(blank=True, null=True)),
                ('irm_user_id', models.IntegerField(blank=True, null=True)),
                ('irm_source_system_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'irm_job_master',
                'managed': False,
            },
        ),
    ]
