DELETE FROM `fnd_application_vl`;
DELETE FROM `fnd_concurrent_programs_vl`;
DELETE FROM `fnd_data_groups`;
DELETE FROM `fnd_form_functions_vl`;
DELETE FROM `fnd_menu_entries_vl`;
DELETE FROM `fnd_menus_vl`;
DELETE FROM `fnd_nodes`;
DELETE FROM `fnd_profile_options`;
DELETE FROM `fnd_profile_options_tl`;
