# Generated by Django 3.0.3 on 2020-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrmAppUsers',
            fields=[
                ('irm_user_id', models.AutoField(db_column='IRM_USER_ID', primary_key=True, serialize=False)),
                ('app_username', models.CharField(db_column='APP_USERNAME', max_length=45)),
                ('app_pass_encrypt', models.TextField(db_column='APP_PASS_ENCRYPT')),
                ('is_active', models.CharField(db_column='IS_ACTIVE', max_length=1)),
                ('user_fname', models.CharField(db_column='USER_FNAME', max_length=100)),
                ('user_lname', models.CharField(db_column='USER_LNAME', max_length=100)),
                ('user_email', models.CharField(db_column='USER_EMAIL', max_length=100)),
                ('user_contact_num', models.CharField(blank=True, db_column='USER_CONTACT_NUM', max_length=45, null=True)),
                ('crd_date', models.DateTimeField(blank=True, db_column='CRD_DATE', null=True)),
                ('upd_date', models.DateTimeField()),
                ('crd_usr_id', models.IntegerField(blank=True, db_column='CRD_USR_ID', null=True)),
                ('upd_usr_id', models.IntegerField(blank=True, db_column='UPD_USR_ID', null=True)),
            ],
            options={
                'db_table': 'irm_app_users',
                'managed': False,
            },
        ),
    ]
