# Generated by Django 3.0.3 on 2020-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrmModuleMst',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('module_code', models.CharField(blank=True, max_length=45, null=True)),
                ('module_type', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('crd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField()),
                ('crd_usr_id', models.IntegerField(blank=True, null=True)),
                ('upd_usr_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'irm_module_mst',
                'managed': False,
            },
        ),
    ]
